// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "e0019dd77912e5d8e632587a70080d7db561445afb09b30acbaeef766eb06c25")
